# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestMySqlModel', '0002_auto_20170627_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='kyage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
