# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestMySqlModel', '0004_auto_20170627_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='kage',
            field=models.CharField(max_length=10),
        ),
    ]
